version: "3.8"
services:
  app:
    image: node:14-alpine
    container_name: rentAlx
    restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3333:3333"
    command: yarn dev
  # database-one:
  #   image: mongo
  #   container_name: database-one
  #   restart: always
  #   ports: 
  #     - 27017:27017