version: "3.8"
services:
  app:
    image: node:14-alpine
    container_name: rentAlx
    restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3333:3333"
    command: yarn dev
    depends_on:
      - database-ps
  database-ps:
    image: postgres
    container_name: database-ps
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local